### ISSUE TITLE
KeyError: 'volume'

### ISSUE THREAD

**Issue by ZZUzy** [microsoft/Recursive-Cascaded-Networks#74]
Traceback (most recent call last):
  File "train.py", line 242, in <module>
    main()
  File "train.py", line 182, in main
    fd = next(generator)
  File "D:\Recursive-Cascaded-Networks-master\data_util\brain.py", line 123, in generator
    ret['voxel1'][i, ..., 0], ret['voxel2'][i, ...,0] = d1['volume'], d2['volume']
KeyError: 'volume'

When I encountered such a problem while running the code, is there anyone who met the same situation as me and has solved it?

**Comment by ZZUzy** [comment]
I also have the same problem. Is there any solution？
